documents = [

    # AI Documents (20)

    "What is Artificial Intelligence?",
    "What is Machine Learning?",
    "What is Deep Learning?",
    "What is Prompt Engineering?",
    "What is Retrieval Augmented Generation?",
    "What are Embeddings?",
    "How do Transformers work?",
    "What is Fine Tuning?",
    "What is LangChain?",
    "What is a Vector Database?",
    "What is an AI Agent?",
    "What is Natural Language Processing?",
    "How does ChatGPT work?",
    "What is Semantic Search?",
    "What is Reinforcement Learning?",
    "What is Computer Vision?",
    "What is Tokenization?",
    "How do LLMs generate responses?",
    "What is Supervised Learning?",
    "What is Unsupervised Learning?",

    # Sports Documents (20)

    "Football is played with eleven players.",
    "Cricket is a bat and ball sport.",
    "Basketball involves shooting a ball through a hoop.",
    "Tennis is played with rackets.",
    "The FIFA World Cup is a football tournament.",
    "Virat Kohli is a cricket player.",
    "Lionel Messi is a football player.",
    "LeBron James is a basketball player.",
    "The Olympics host many sports.",
    "A football match lasts ninety minutes.",
    "A cricket innings can last many overs.",
    "Basketball has four quarters.",
    "Tennis Grand Slams are major tournaments.",
    "Swimming is an Olympic sport.",
    "Running improves endurance.",
    "Football requires teamwork.",
    "Cricket involves batting and bowling.",
    "Basketball emphasizes agility.",
    "Tennis requires quick reflexes.",
    "Sports improve physical fitness.",

    # Finance Documents (20)

    "Stocks represent ownership in a company.",
    "Mutual funds pool investor money.",
    "Bonds are fixed income investments.",
    "Diversification reduces investment risk.",
    "The stock market allows trading of shares.",
    "Inflation affects purchasing power.",
    "Interest rates influence borrowing costs.",
    "Budgeting helps manage personal finance.",
    "Financial planning supports long term goals.",
    "Saving money creates financial security.",
    "Investing can grow wealth over time.",
    "Exchange traded funds track indexes.",
    "Risk and return are related concepts.",
    "Compound interest accelerates growth.",
    "A portfolio contains multiple assets.",
    "Banks provide financial services.",
    "Credit scores affect loan approval.",
    "Retirement planning is important.",
    "Economic growth influences markets.",
    "Asset allocation balances investments."
]